service: pricecheck

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  timeout: 30
  versionFunctions: false
  region: ap-southeast-1
  tags:
    Project: pricecheck
functions:
  tcgplayer:
    handler: main.tcg_handler
    environment:
      client_id: ${ssm:tcgplayer_client_id}
      client_secret: ${ssm:tcgplayer_client_secret}
    layers:
      - arn:aws:lambda:ap-southeast-1:549791063841:layer:mtg-price-layer:2
    events:
      - http:
          path: tcgplayer
          cors: true
          method: get
          querystrings:
            querystring: true
  bigweb:
    handler: main.big_handler
    layers:
      - arn:aws:lambda:ap-southeast-1:549791063841:layer:mtg-price-layer:2
    events:
      - http:
          path: bigweb
          cors: true
          method: get
          querystrings:
            querystring: true
resources:
  Outputs:
    APIEndpoint:
      Description: URL of the API Endpoint
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${opt:region, self:provider.region}.amazonaws.com/${opt:stage}"
      Export:
        Name: ${self:service}:${opt:stage}:APIEndpoint      