service: pricecheck

provider:
  name: aws
  runtime: python3.6
  timeout: 30
  versionFunctions: false
  region: ap-southeast-1
  tags:
    Project: pricecheck
functions:
  tcgplayer:
    handler: main.tcg_handler
    memorySize: 256
    environment:
      client_id: ${ssm:tcgplayer_client_id}
      client_secret: ${ssm:tcgplayer_client_secret}
    layers:
      - arn:aws:lambda:ap-southeast-1:549791063841:layer:mtg-price-layer:2
    events:
      - http:
          path: tcgplayer/{querystring}
          cors: true
          method: get
          request:
            parameters:
              querystring: true
  bigweb:
    handler: main.big_handler
    memorySize: 512
    layers:
      - arn:aws:lambda:ap-southeast-1:549791063841:layer:mtg-price-layer:2
    events:
      - http:
          path: bigweb/{querystring}
          cors: true
          method: get
          request:
            parameters:
              querystring: true
resources:
  Resources:
    ServiceEndpointParameter:
      Type: AWS::SSM::Parameter 
      Properties: 
        Description: "URL of the service endpoint"
        Name: ${self:service}_${opt:stage, self:provider.stage}_ServiceEndpoint  
        Type: "String"
        Value: 
          Fn::Join:
            - ""
            - - "https://"
              - Ref: ApiGatewayRestApi
              - ".execute-api.${opt:region, self:provider.region}.amazonaws.com/${opt:stage, self:provider.stage}"
  Outputs:
    ParameterName:
      Description: Name of the Service endpoint paramter
      Value:
        Ref: ServiceEndpointParameter
      Export:
        Name: ${self:service}-${opt:stage, self:provider.stage}-ParameterName
